# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 09:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('start', models.DateTimeField(verbose_name='starts at')),
                ('end', models.DateTimeField(verbose_name='ends at')),
                ('description', models.TextField(blank=True, max_length=3000, null=True, verbose_name='description')),
                ('price', models.PositiveIntegerField(blank=True, null=True, verbose_name='price')),
                ('status', models.IntegerField(choices=[(1, 'open'), (2, 'cancelled'), (3, 'postponed'), (4, 'closed')], default=1, verbose_name='status')),
                ('location', models.CharField(blank=True, default='tel aviv', max_length=50, null=True, verbose_name='location')),
                ('longitude', models.DecimalField(blank=True, decimal_places=12, max_digits=16, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=12, max_digits=16, null=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='host')),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('status', models.IntegerField(choices=[(1, 'no response'), (2, 'accepted'), (3, 'declined'), (4, 'maybe')], default=1, verbose_name='response')),
                ('invited_at', models.DateTimeField(verbose_name='invited_at')),
                ('secret_code', models.CharField(max_length=200, unique=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event', verbose_name='event')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitees', to=settings.AUTH_USER_MODEL, verbose_name='invited_by')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('slot_num', models.IntegerField(verbose_name='number of slots')),
                ('comment', models.CharField(max_length=200, verbose_name='comment')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='events.Event', verbose_name='event')),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=100, null=True, verbose_name='comment')),
                ('index', models.PositiveIntegerField(blank=True, null=True)),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slots', to=settings.AUTH_USER_MODEL, verbose_name='filled by')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='events.Item', verbose_name='item')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='guest',
            unique_together=set([('event', 'email')]),
        ),
    ]
