# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='status',
            field=models.IntegerField(),
        ),
    ]
