# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 23:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20160604_0236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='secret_code',
        ),
    ]
