# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20160602_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='index',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
