# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20160601_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventguests',
            name='can_edit',
            field=models.BooleanField(default=False),
        ),
    ]
