# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_guest_secret_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='secret_code',
            field=models.CharField(default=2, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='guest',
            name='status',
            field=models.IntegerField(choices=[(1, 'no response'), (2, 'accepted'), (3, 'declined'), (4, 'maybe')], default=1),
        ),
    ]
