# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 11:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0003_slot_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.IntegerField(choices=[(1, 'no response'), (2, 'accepted'), (3, 'declined'), (4, 'maybe')], default=1)),
                ('invited_at', models.DateTimeField()),
                ('secret_code', models.CharField(max_length=200)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitees', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='eventguests',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='eventguests',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventguests',
            name='guest',
        ),
        migrations.DeleteModel(
            name='EventGuests',
        ),
    ]
