# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20160602_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='secret_code',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='guest',
            unique_together=set([('event', 'email')]),
        ),
    ]
