# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 20:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20160601_2310'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventguests',
            unique_together=set([('guest', 'event')]),
        ),
    ]
