# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 08:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20160602_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.DateTimeField(verbose_name='ends at'),
        ),
        migrations.AlterField(
            model_name='event',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='host'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, default='tel aviv', max_length=50, null=True, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.DateTimeField(verbose_name='starts at'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.IntegerField(choices=[(1, 'open'), (2, 'cancelled'), (3, 'postponed'), (4, 'closed')], default=1, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=50, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event', verbose_name='event'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='invited_at',
            field=models.DateTimeField(verbose_name='invited_at'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='invited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitees', to=settings.AUTH_USER_MODEL, verbose_name='invited_by'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='name',
            field=models.CharField(max_length=200, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='status',
            field=models.IntegerField(choices=[(1, 'no response'), (2, 'accepted'), (3, 'declined'), (4, 'maybe')], default=1, verbose_name='response'),
        ),
        migrations.AlterField(
            model_name='item',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='item',
            name='comment',
            field=models.CharField(max_length=200, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='item',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='events.Event', verbose_name='event'),
        ),
        migrations.AlterField(
            model_name='item',
            name='slot_num',
            field=models.IntegerField(verbose_name='number of slots'),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=50, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='comment',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slots', to=settings.AUTH_USER_MODEL, verbose_name='filled by'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='events.Item', verbose_name='item'),
        ),
    ]
